apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otelcol-ebpf-profiler
  namespace: default
  labels:
    app: otelcol-ebpf-profiler
spec:
  selector:
    matchLabels:
      app: otelcol-ebpf-profiler
  template:
    metadata:
      labels:
        app: otelcol-ebpf-profiler
    spec:
      hostPID: true
      tolerations:
        - operator: Exists
      containers:
        - name: otelcol-ebpf-profiler
          image: otelcol-ebpf-profiler:local
          imagePullPolicy: Never
          args:
            - "--config=/etc/otelcol/config.yaml"
            - "--feature-gates=+service.profilesSupport"
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: debugfs
              mountPath: /sys/kernel/debug
      volumes:
        - name: config
          configMap:
            name: otelcol-ebpf-profiler-config
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
